name: sam_sql
channels:
  - conda-forge
dependencies:
  - ipykernel
  - sqlalchemy
  - conda-tree
  - pandas
  - pip
  - mysql
  - pymssql
  - pymysql
  - mysql-connector-python
  - matplotlib
  - nbconvert
  - pip:
      - dotenv
      - pipdeptree
