name: sam_sql
channels:
  - conda-forge
dependencies:
  - python
  - mysql
  - mysql-connector-python
  - coreutils
  - postgresql=18.*
  - pip
  # docs/presentation deps:
  - quarto
  - eralchemy2
  - pydeps
  - pip:
      - pipdeptree
