#-------------------------------------------------------------------------bh-
#-------------------------------------------------------------------------eh-

from typing import Optional
from sqlalchemy import (
    Column, Integer, String, Float, DateTime, Date, Boolean, Numeric,
    ForeignKey, Index, MetaData, Text, BigInteger, TIMESTAMP, text, and_, or_
)
from sqlalchemy.orm import relationship, declarative_base, declared_attr, Session
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.sql import func

from sam.fmt import utcnow_naive  # status timestamps are naive-UTC, not local
import os


# ============================================================================
# Naming convention — stable across MySQL, Postgres, and SQLite.
#
# Alembic autogenerate emits explicit constraint names from these templates,
# so migrations are portable across dialects. Applies to the standalone
# declarative_base() used by `alembic` (FLASK_ACTIVE unset). Existing
# models already use explicit constraint names; this convention only
# affects newly autogenerated names going forward.
# ============================================================================
STATUS_NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


#-------------------------------------------------------------------------bm-
def _get_status_base_class():
    """
    Get appropriate base class for system_status models.

    Returns:
        - Flask-SQLAlchemy's db.Model if FLASK_ACTIVE=1 (Flask context)
        - SQLAlchemy's declarative_base() with STATUS_NAMING_CONVENTION
          metadata otherwise (CLI / Alembic / standalone tests).
    """
    if os.environ.get('FLASK_ACTIVE') == '1':
        try:
            from webapp.extensions import db
            return db.Model
        except ImportError as exc:
            # Fallback if webapp not available — almost certainly a broken
            # environment rather than an intended CLI run: Flask-SQLAlchemy
            # will NOT see models bound to this standalone base.
            import logging
            logging.getLogger(__name__).warning(
                "FLASK_ACTIVE=1 but webapp.extensions is not importable (%s); "
                "system_status models are binding to a standalone "
                "declarative_base.", exc)
            metadata = MetaData(naming_convention=STATUS_NAMING_CONVENTION)
            return declarative_base(metadata=metadata)
    else:
        # CLI / Alembic / standalone context
        metadata = MetaData(naming_convention=STATUS_NAMING_CONVENTION)
        return declarative_base(metadata=metadata)

StatusBase = _get_status_base_class()

# ============================================================================
# Mixins - Common patterns for system status tracking
# ============================================================================

class StatusTimestampMixin:
    """Provides timestamp field for status snapshots."""

    @declared_attr
    def timestamp(cls):
        return Column(DateTime, nullable=False, index=True)

    @declared_attr
    def created_at(cls):
        return Column(DateTime, nullable=False, default=utcnow_naive,
                     server_default=text('CURRENT_TIMESTAMP'))


class StatusSnapshotMixin(StatusTimestampMixin):
    """
    Mixin for time-series status tables.
    Provides timestamp indexing and snapshot identification.
    """
    pass


class AvailabilityMixin:
    """Provides availability status tracking."""

    @declared_attr
    def available(cls):
        return Column(Boolean, nullable=False, default=True)

    @declared_attr
    def degraded(cls):
        return Column(Boolean, nullable=False, default=False)

    @property
    def is_available(self) -> bool:
        """Check if resource is fully available."""
        return bool(self.available and not self.degraded)

    @property
    def status_name(self) -> str:
        """Get human-readable status name."""
        if not self.available:
            return "offline"
        elif self.degraded:
            return "degraded"
        else:
            return "online"


class SessionMixin:
    """Provides access to SQLAlchemy session."""

    @property
    def session(self) -> Session:
        s = Session.object_session(self)
        return s


class QueueRollupMetricsMixin:
    """Per-queue rollup metric columns shared by ``QueueStatus`` and
    ``UserProjQueueStatus``.

    The two tables capture the same counters at different aggregation grains:
    ``QueueStatus`` collapses across users/projects, ``UserProjQueueStatus``
    keys by ``(user, project_code, queue)``. Keeping the columns in a mixin
    avoids drift if a new metric is added.

    ``active_users`` is intentionally NOT part of the mixin — it's only
    meaningful at the queue grain (one row per user, by definition, in the
    per-user table).
    """

    @declared_attr
    def running_jobs(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def pending_jobs(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def held_jobs(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def cores_allocated(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def gpus_allocated(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def nodes_allocated(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def cores_pending(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def gpus_pending(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def cores_held(cls):
        return Column(Integer, nullable=False, default=0)

    @declared_attr
    def gpus_held(cls):
        return Column(Integer, nullable=False, default=0)
#-------------------------------------------------------------------------em-
