{{- if .Values.webapp.dbCredentials.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.webapp.name }}-db-credentials-esos
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.webapp.dbCredentials.secretStoreRefName }}
    kind: SecretStore
  target:
    name: {{ .Values.webapp.name }}-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.webapp.dbCredentials.secretPath }}
        property: {{ .Values.webapp.dbCredentials.usernameKey }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.webapp.dbCredentials.secretPath }}
        property: {{ .Values.webapp.dbCredentials.passwordKey }}
{{- end }}