{{- if and .Values.webapp.dbCredentials.enabled .Values.webapp.dbCredentials.useExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.webapp.name }}-db-credentials-esos
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.webapp.dbCredentials.secretStoreRefName }}
    kind: SecretStore
  target:
    name: {{ .Values.webapp.name }}-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.webapp.dbCredentials.secretPath }}
        property: {{ .Values.webapp.dbCredentials.usernameKey }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.webapp.dbCredentials.secretPath }}
        property: {{ .Values.webapp.dbCredentials.passwordKey }}
{{- end }}

{{- if and .Values.webapp.samDbCredentials.enabled .Values.webapp.samDbCredentials.useExternalSecret }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.webapp.name }}-sam-db-credentials-esos
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.webapp.samDbCredentials.secretStoreRefName }}
    kind: SecretStore
  target:
    name: {{ .Values.webapp.name }}-sam-db-credentials
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.webapp.samDbCredentials.secretPath }}
        property: {{ .Values.webapp.samDbCredentials.usernameKey }}
    - secretKey: password
      remoteRef:
        key: {{ .Values.webapp.samDbCredentials.secretPath }}
        property: {{ .Values.webapp.samDbCredentials.passwordKey }}
{{- end }}

{{- if and .Values.webapp.jupyterhubCredentials.enabled .Values.webapp.jupyterhubCredentials.useExternalSecret }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.webapp.name }}-jh-credentials-esos
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.webapp.jupyterhubCredentials.secretStoreRefName }}
    kind: SecretStore
  target:
    name: {{ .Values.webapp.name }}-jh-credentials
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.webapp.jupyterhubCredentials.secretPath }}
        property: {{ .Values.webapp.jupyterhubCredentials.tokenKey }}
{{- end }}
