"""Declarative CRUD registrar for simple admin card entities.

Most entities on the admin cards (Organizations, Facilities, Resources)
repeat the same five routes — edit-form GET, edit POST, create-form GET,
create POST, soft-delete DELETE — differing only in model, schema, URL
slug, templates, and dropdown context. `CrudSpec` captures those axes;
`register_crud` emits the quintet with endpoints and URL rules IDENTICAL
to the hand-written view functions they replace, so template `url_for`
calls and htmx attributes are untouched.

**Hard rule: an entity needing more than the spec expresses stays a
bespoke route.** Do not grow this spec new axes to absorb one special
case — the mnemonic-code create (DB uniqueness checks), the contract
delete (retire-by-end_date), and the panel-session edit (ORM cross-field
check) are examples that stay hand-written next to their specs.

Behavioral contract preserved from the hand-written routes:
  * edit-form GET for a missing id → warning div at 200 (htmx swaps it
    into the modal body); POST/DELETE for a missing id → 404
    (`htmx_not_found`).
  * POST bodies delegate to `handle_htmx_form_post` — schema validation,
    `management_transaction`, inline field errors, HX-Trigger success.
  * DELETE delegates to `handle_htmx_soft_delete` (sets active=False).
"""

from dataclasses import dataclass, field
from typing import Callable, Optional

from flask import render_template
from flask_login import login_required

from webapp.extensions import db
from webapp.utils.htmx import (
    handle_htmx_form_post,
    handle_htmx_soft_delete,
    htmx_not_found,
)
from webapp.utils.rbac import Permission, require_permission


@dataclass(frozen=True)
class CrudSpec:
    """Declarative description of one admin CRUD entity.

    Field-projection rules: an action's kwargs callable wins when set;
    otherwise ``{f: data[f] for f in *_fields}`` is used. Context
    callables are re-run on every render (GET form and error re-render),
    so dropdown queries stay fresh.
    """

    slug: str                     # URL slug, e.g. 'institution-type'
    name: str                     # display name for not-found messages
    model: type                   # ORM class (create() classmethod, update() method)
    id_param: str                 # URL kwarg name, e.g. 'institution_type_id'
    context_key: str              # template var holding the entity, e.g. 'inst_type'
    edit_schema: Optional[type] = None
    create_schema: Optional[type] = None
    edit_fields: tuple = ()       # data keys forwarded to obj.update(**)
    create_fields: tuple = ()     # data keys forwarded to Model.create(session, **)
    edit_kwargs: Optional[Callable] = None    # data -> dict, overrides edit_fields
    create_kwargs: Optional[Callable] = None  # data -> dict, overrides create_fields
    edit_context: Optional[Callable] = None   # () -> dict (form GET + error re-render)
    create_context: Optional[Callable] = None
    triggers: dict = field(default_factory=dict)  # HX-Trigger success payload
    edit_permission: Optional[Permission] = None
    create_permission: Optional[Permission] = None
    delete_permission: Optional[Permission] = None
    after_commit: Optional[Callable] = None   # result -> None, post-commit hook
    actions: tuple = ('edit', 'create', 'delete')
    endpoint_base: Optional[str] = None   # default: slug with '-' → '_'
    noun: Optional[str] = None    # error-message noun; default name.lower()
    edit_template: Optional[str] = None   # default derived from endpoint_base
    create_template: Optional[str] = None


def register_crud(bp, spec: CrudSpec):
    """Register the CRUD route quintet for ``spec`` on blueprint ``bp``."""
    base = spec.endpoint_base or spec.slug.replace('-', '_')
    noun = spec.noun or spec.name.lower()
    edit_template = (spec.edit_template
                     or f'dashboards/admin/fragments/edit_{base}_form_htmx.html')
    create_template = (spec.create_template
                       or f'dashboards/admin/fragments/create_{base}_form_htmx.html')

    def _register(action, rule, endpoint, permission, view, **options):
        view.__name__ = endpoint
        view.__doc__ = f'{action} {noun} ({spec.model.__name__}) — generated by register_crud.'
        bp.add_url_rule(rule, endpoint=endpoint,
                        view_func=login_required(require_permission(permission)(view)),
                        **options)

    if 'edit' in spec.actions:
        def edit_form(**kwargs):
            obj = db.session.get(spec.model, kwargs[spec.id_param])
            if not obj:
                return f'<div class="alert alert-warning">{spec.name} not found</div>'
            ctx = {spec.context_key: obj}
            if spec.edit_context is not None:
                ctx.update(spec.edit_context())
            return render_template(edit_template, **ctx)

        def edit(**kwargs):
            obj = db.session.get(spec.model, kwargs[spec.id_param])
            if not obj:
                return htmx_not_found(spec.name)
            return handle_htmx_form_post(
                schema_cls=spec.edit_schema,
                template=edit_template,
                success_triggers=spec.triggers,
                error_prefix=f'Error updating {noun}',
                extra_context={spec.context_key: obj},
                context_fn=spec.edit_context,
                after_commit=spec.after_commit,
                do_action=lambda data: obj.update(
                    **(spec.edit_kwargs(data) if spec.edit_kwargs
                       else {f: data[f] for f in spec.edit_fields})),
            )

        _register('Edit form for', f'/htmx/{spec.slug}-edit-form/<int:{spec.id_param}>',
                  f'htmx_{base}_edit_form', spec.edit_permission, edit_form)
        _register('Update', f'/htmx/{spec.slug}-edit/<int:{spec.id_param}>',
                  f'htmx_{base}_edit', spec.edit_permission, edit,
                  methods=['POST'])

    if 'create' in spec.actions:
        def create_form(**kwargs):
            ctx = spec.create_context() if spec.create_context is not None else {}
            return render_template(create_template, **ctx)

        def create(**kwargs):
            return handle_htmx_form_post(
                schema_cls=spec.create_schema,
                template=create_template,
                success_triggers=spec.triggers,
                error_prefix=f'Error creating {noun}',
                context_fn=spec.create_context,
                after_commit=spec.after_commit,
                do_action=lambda data: spec.model.create(
                    db.session,
                    **(spec.create_kwargs(data) if spec.create_kwargs
                       else {f: data[f] for f in spec.create_fields})),
            )

        _register('Create form for', f'/htmx/{spec.slug}-create-form',
                  f'htmx_{base}_create_form', spec.create_permission, create_form)
        _register('Create', f'/htmx/{spec.slug}-create',
                  f'htmx_{base}_create', spec.create_permission, create,
                  methods=['POST'])

    if 'delete' in spec.actions:
        def delete(**kwargs):
            obj = db.session.get(spec.model, kwargs[spec.id_param])
            if not obj:
                return htmx_not_found(spec.name)
            response = handle_htmx_soft_delete(obj, name=spec.name)
            if response == '' and spec.after_commit is not None:
                spec.after_commit(obj)
            return response

        _register('Soft-delete', f'/htmx/{spec.slug}-delete/<int:{spec.id_param}>',
                  f'htmx_{base}_delete', spec.delete_permission, delete,
                  methods=['DELETE'])
