apiVersion: v2
name: samuel                             # Name of this Helm chart
description: A Helm chart for deploying a web application to CIRRUS
type: application                        # Application chart (not a library)
version: 0.0.1                           # Chart version, increment when you change templates
appVersion: "0.0.1"                      # Your application version, increment when you update your image
